import type { Config } from "tailwindcss";

// Verbatim port of the design tokens from reference/ivr-automation-page.html
// (lines 6-89 of the mockup's inline tailwind.config script). Do not
// reinterpret these values — they are the source of truth for the UI.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e4e1e6",
        "on-error-container": "#ffdad6",
        tertiary: "#c8c5cc",
        "on-tertiary-fixed": "#1b1b20",
        "on-secondary-container": "#b6b4b8",
        primary: "#FF693D",
        surface: "#050505",
        "secondary-fixed-dim": "#c8c5ca",
        "tertiary-container": "#9a989f",
        "surface-tint": "#FF693D",
        "on-surface-variant": "#a1a1aa",
        error: "#ffb4ab",
        "tertiary-fixed": "#e4e1e8",
        outline: "#27272a",
        "outline-variant": "#18181b",
        "inverse-primary": "#af3005",
        secondary: "#c8c5ca",
        "inverse-on-surface": "#2f3037",
        "on-surface": "#fafafa",
        "surface-variant": "#09090b",
        "on-tertiary-fixed-variant": "#47464c",
        "primary-fixed-dim": "#ffb5a0",
        "surface-container-highest": "#18181b",
        "on-tertiary": "#303035",
        "on-error": "#690005",
        "on-primary-container": "#ffffff",
        background: "#050505",
        "inverse-surface": "#e2e1eb",
        "on-primary-fixed-variant": "#872100",
        "on-tertiary-container": "#313136",
        "primary-container": "#FF693D",
        "surface-dim": "#050505",
        "secondary-container": "#27272a",
        "on-primary": "#000000",
        "surface-container-high": "#111111",
        "surface-container-lowest": "#050505",
        "tertiary-fixed-dim": "#c8c5cc",
        "on-secondary-fixed": "#1b1b1e",
        "primary-fixed": "#ffdbd1",
        "on-primary-fixed": "#3b0900",
        "error-container": "#93000a",
        "surface-container": "#09090b",
        "surface-bright": "#111111",
        "on-secondary-fixed-variant": "#47464a",
        "on-background": "#fafafa",
        "surface-container-low": "#09090b",
        "on-secondary": "#303033",
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "6px",
        xl: "8px",
        full: "9999px",
      },
      spacing: {
        sm: "16px",
        gutter: "24px",
        xs: "8px",
        base: "4px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        margin: "32px",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "label-caps": ["Inter"],
        "title-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
