"""Repository Pattern contracts. One Protocol per entity; concrete
implementations live in app/repositories/ and are wired via FastAPI's
Depends() graph (app/api/deps.py) or, for Celery tasks, a manual factory."""

import uuid
from typing import Any, Protocol

from app.domain.entities import (
    AudioFileEntity,
    BatchEntity,
    JobEntity,
    LanguageEntity,
    LogEntity,
    ProjectEntity,
    ScriptEntity,
    TranslationEntity,
    UserEntity,
    VoiceEntity,
)


class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> UserEntity | None: ...
    async def get(self, user_id: uuid.UUID) -> UserEntity | None: ...
    async def create(self, email: str, display_name: str | None = None) -> UserEntity: ...


class ProjectRepository(Protocol):
    async def get(self, project_id: uuid.UUID) -> ProjectEntity | None: ...
    async def get_or_create_default(self, module: str, name: str) -> ProjectEntity: ...


class LanguageRepository(Protocol):
    async def list_active(self) -> list[LanguageEntity]: ...
    async def get(self, code: str) -> LanguageEntity | None: ...
    async def resolve_detector_alias(self, alias: str) -> LanguageEntity | None: ...
    async def resolve_header_synonym(self, token: str) -> LanguageEntity | None: ...


class VoiceRepository(Protocol):
    async def list_active(self, language_code: str | None = None) -> list[VoiceEntity]: ...
    async def get(self, voice_id: uuid.UUID) -> VoiceEntity | None: ...
    async def get_by_preset_key(self, preset_key: str) -> VoiceEntity | None: ...
    async def first_active_for_language(self, language_code: str) -> VoiceEntity | None: ...
    async def get_fallback(self) -> VoiceEntity | None: ...


class BatchRepository(Protocol):
    async def create(self, **fields: Any) -> BatchEntity: ...
    async def get(self, batch_id: uuid.UUID) -> BatchEntity | None: ...
    async def update(self, batch_id: uuid.UUID, **fields: Any) -> None: ...
    async def increment_counters(
        self, batch_id: uuid.UUID, *, completed_delta: int = 0, failed_delta: int = 0
    ) -> None: ...
    async def recompute_job_counts(self, batch_id: uuid.UUID) -> tuple[int, int]:
        """Returns (completed_count, failed_count) computed fresh from the
        jobs table -- the source of truth used at finalize time, not the
        incrementally-maintained counters."""
        ...


class ScriptRepository(Protocol):
    async def bulk_create(self, batch_id: uuid.UUID, rows: list[dict[str, Any]]) -> list[ScriptEntity]: ...
    async def list_by_batch(self, batch_id: uuid.UUID) -> list[ScriptEntity]: ...
    async def get(self, script_id: uuid.UUID) -> ScriptEntity | None: ...
    async def update(self, script_id: uuid.UUID, **fields: Any) -> None: ...


class TranslationRepository(Protocol):
    async def create(self, **fields: Any) -> TranslationEntity: ...
    async def get(self, translation_id: uuid.UUID) -> TranslationEntity | None: ...
    async def update(self, translation_id: uuid.UUID, **fields: Any) -> None: ...


class JobRepository(Protocol):
    async def bulk_create(self, rows: list[dict[str, Any]]) -> list[JobEntity]: ...
    async def list_by_batch(self, batch_id: uuid.UUID) -> list[JobEntity]: ...
    async def list_by_stage(self, batch_id: uuid.UUID, stage: str) -> list[JobEntity]: ...
    async def get(self, job_id: uuid.UUID) -> JobEntity | None: ...
    async def update(self, job_id: uuid.UUID, **fields: Any) -> None: ...
    async def count_by_stage(self, batch_id: uuid.UUID) -> dict[str, int]: ...


class AudioFileRepository(Protocol):
    async def create(self, **fields: Any) -> AudioFileEntity: ...
    async def list_by_batch(self, batch_id: uuid.UUID) -> list[AudioFileEntity]: ...


class LogRepository(Protocol):
    async def create(
        self,
        batch_id: uuid.UUID,
        message: str,
        *,
        level: str = "info",
        script_id: uuid.UUID | None = None,
        job_id: uuid.UUID | None = None,
        context: dict[str, Any] | None = None,
    ) -> LogEntity: ...
    async def list_by_batch(self, batch_id: uuid.UUID) -> list[LogEntity]: ...
